# Generated by Django 4.2.2 on 2023-06-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_userreview_negative_reviews_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilityfeature",
            name="category",
            field=models.CharField(
                choices=[
                    ("wheelchair", "Wheelchair"),
                    ("handrail", "Handrail"),
                    ("tactile_paving", "Tactile Paving"),
                    ("accessible_parking", "Accessible Parking"),
                    ("accessible_restroom", "Accessible Restroom"),
                ],
                max_length=25,
            ),
        ),
    ]
